Changes: small changes and source format update
Signed-off-by: Miroslav Safr <Miroslav.Safr@gmail.com>

diff --git a/gr-pullreset b/gr-pullreset
--- a/gr-pullreset
+++ b/gr-pullreset
@@ -24,7 +24,7 @@ usage() {
 while [ $# -gt 0 ]; do
   case "$1" in
     -V|--version)         echo "`basename $0` ${VERSION} ${VERSION_DATE}" ; exit 0 ;;
-    -h|--help)            usage ; exit ;;
+    -h|--help)            usage ; exit 0 ;;
     -ls|--line-separator) LINE_SEPARATOR=1 ;;
     -ns|--no-summary)     NO_SUMMARY=1 ;;
 	-b|--branch)		  USER_BRANCH=$1 ;;
@@ -33,65 +33,64 @@ while [ $# -gt 0 ]; do
   shift
 done
 if [ -z "$PROJECT_DIR" ]; then
-        PROJECT_DIR="./"
+    PROJECT_DIR="./"
 fi
 
 if [ ! -d "$PROJECT_DIR" ]; then
-  echo "directory $PROJECT_DIR does not exist";
-  exit 1
+  echo "directory $PROJECT_DIR does not exist" ; exit 1
 fi
 
 CWD=`pwd`
-cd $PROJECT_DIR
+cd "$PROJECT_DIR"
 PROJECT_DIR=`pwd`
 
 find "$PROJECT_DIR" -type d -name ".git*"  |  sed 's/\/.git//g' | sort | while read ENTRY
 do
         PROJECT20=`basename $ENTRY`
         PROJECT20=`printf '\e[1m%-22.22s\e[21m' $PROJECT20`
-        if [ ! -f $ENTRY/.git/skip ]; then
-                cd $ENTRY 
-                if [ ! -z "$LINE_SEPARATOR" ]; then 
-                     echo "\033[44m $(tput el) $(tput sgr0)"
-                fi
-                LASTTAG=`git describe --tags --dirty=* --always 2> /dev/null`
-				BRANCH=`git branch | egrep "^\*" | cut -d' ' -f2`
-                BRANCH20=`printf '%-22.22s' [$BRANCH]`
-                echo "\033[32m$PROJECT20\033[0m \033[31m$BRANCH20\033[0m from: \033[01;34m $LASTTAG \033[0m \c" 
-                [ -n "$USER_BRANCH" -a "$USER_BRANCH" != "$BRANCH" ] && BRANCH=$USER_BRANCH && echo "Switching to user defined branch: $BRANCH"
+        if [ ! -f "$ENTRY/.git/skip" ]; then
+            cd "$ENTRY"
+            if [ ! -z "$LINE_SEPARATOR" ]; then 
+                echo "\033[44m $(tput el) $(tput sgr0)"
+            fi
+            LASTTAG=`git describe --tags --dirty=* --always 2> /dev/null`
+			BRANCH=`git branch | egrep "^\*" | cut -d' ' -f2`
+            BRANCH20=`printf '%-22.22s' [$BRANCH]`
+            echo "\033[32m$PROJECT20\033[0m \033[31m$BRANCH20\033[0m from: \033[01;34m $LASTTAG \033[0m \c" 
+            [ -n "$USER_BRANCH" -a "$USER_BRANCH" != "$BRANCH" ] && BRANCH=$USER_BRANCH && echo "Switching to user defined branch: $BRANCH"
 
-                git fetch origin 2> /dev/null
-                if [ $? = 128 ] ; then
-                    echo "remote \033[41mNOT CONNECTED\033[0m "
-                else
-                    echo
-                    git fetch origin --tags
-                    git reset --hard origin/$BRANCH
-                    git gc --quiet
-                    git pull
-                    if [ $? != 0 ]; then
-                         echo "\033[41mPULL FAILED, FIX CONFLICT MANUALLY\033[0m"  
-                    fi
-                fi
+            git fetch origin 2> /dev/null
+            if [ $? = 128 ] ; then
+                echo "remote \033[41mNOT CONNECTED\033[0m "
+            else
+            echo
+            git fetch origin --tags
+            git reset --hard origin/$BRANCH
+            git gc --quiet
+            git pull
+            if [ $? != 0 ]; then
+                 echo "\033[41mPULL FAILED, FIX CONFLICT MANUALLY\033[0m"  
+            fi
+        fi
     
-                TO=`git describe --tags --dirty=* --always 2> /dev/null`
-                if [ "$LASTTAG" != "$TO" ]; then
-                        echo " \033[33mupdated to:\033[0m \033[01;34m $TO \033[0m  "
-                        LASTMSG=`git log -1 --pretty=tformat:'%h %s | %ad' --date=relative`
-                        echo " \033[33m$LASTMSG\033[0m"
-                fi
-                cd $PROJECT_DIR
+        TO=`git describe --tags --dirty=* --always 2> /dev/null`
+        if [ "$LASTTAG" != "$TO" ]; then
+            echo " \033[33mupdated to:\033[0m \033[01;34m $TO \033[0m  "
+            LASTMSG=`git log -1 --pretty=tformat:'%h %s | %ad' --date=relative`
+            echo " \033[33m$LASTMSG\033[0m"
+        fi
+            cd "$PROJECT_DIR"
         else
-                echo "\033[32m$PROJECT20\033[0m \033[35m skipped update \033[0m" 
+            echo "\033[32m$PROJECT20\033[0m \033[35m skipped update \033[0m" 
         fi
 done
 
 if [ -z "$NO_SUMMARY" ]; then
-        if [ ! -z "$LINE_SEPARATOR" ]; then 
-             echo "\033[44m $(tput el) $(tput sgr0)"
-        fi
-        TIME=`date +%H:%M:%S`
-        ELAPSED_TIME=$((`date +'%s'` - $START_TIME))
-        echo "$BASENAME (reset local)  finished:$TIME took:$(($ELAPSED_TIME/60)) min $(($ELAPSED_TIME%60)) s"
+    if [ -n "$LINE_SEPARATOR" ]; then 
+        echo "\033[44m $(tput el) $(tput sgr0)"
+    fi
+    TIME=`date +%H:%M:%S`
+    ELAPSED_TIME=$((`date +'%s'` - $START_TIME))
+    echo "$BASENAME (reset local)  finished:$TIME took:$(($ELAPSED_TIME/60)) min $(($ELAPSED_TIME%60)) s"
 fi
 
